services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mariadb:10.11
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: keycloak
      MYSQL_USER:
      MYSQL_PASSWORD:
    networks:
      - my-network
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER:
      DB_PASSWORD:
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - my-network
    restart: unless-stopped

volumes:
  mysql_keycloak_data:
    driver: local

networks:
  my-network:
    driver: bridge
